question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Vatican City is a country.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "Toronto is the capital city of the North American country of Canada.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography", "question": "Tokyo is the capital of Japan.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "New Haven is the capital city of the state of Connecticut in the United States.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Rhode Island is actually located on the US mainland, despite its name.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                       "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
                                       "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
                                      "question": "There is a city called Rome in every continent on Earth.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography", "question": "California is larger than Japan.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
